POST http://localhost:3001/api/articles
Content-Type: application/json

{
  "title": "Corrected Schema",
  "authors": ["Oli C", "Raya D"],
  "content": "## Lorem ipsum dolor sit amet",
  "userId": "61396fd208fc2d2a1051a346"
}