GET http://localhost:3001/api/articles/6139767a81320d4d80798438

###
GET http://localhost:3001/api/articles/edit/6139767a81320d4d80798438

###
# malformatted id
GET http://localhost:3001/api/articles/1

###
# malformatted id
GET http://localhost:3001/api/articles/edit/1